version: '2.2'

services:
  pg:
    image: postgres:14
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  strapi:
    build:
      context: ./strapi
      dockerfile: ../Dockerfile.strapi
    env_file:
      - .env
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    restart: unless-stopped
    depends_on:
      - "pg"

